//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "course_audit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub course_id: i64,
    pub audit_mind: Option<String>,
    pub audit_status: String,
    pub audit_people: Option<String>,
    pub audit_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
