//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "course_base")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub company_id: i64,
    pub company_name: Option<String>,
    pub name: String,
    pub users: Option<String>,
    pub tags: Option<String>,
    pub mt: String,
    pub st: String,
    pub grade: String,
    pub teachmode: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub pic: Option<String>,
    pub create_date: Option<DateTime>,
    pub change_date: Option<DateTime>,
    pub create_people: Option<String>,
    pub change_people: Option<String>,
    pub audit_status: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
