//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod course_audit;
pub mod course_base;
pub mod course_category;
pub mod course_market;
pub mod course_publish;
pub mod course_publish_pre;
pub mod course_teacher;
pub mod mq_message;
pub mod mq_message_history;
pub mod teachplan;
pub mod teachplan_media;
pub mod teachplan_work;
