//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::course_audit::Entity as CourseAudit;
pub use super::course_base::Entity as CourseBase;
pub use super::course_category::Entity as CourseCategory;
pub use super::course_market::Entity as CourseMarket;
pub use super::course_publish::Entity as CoursePublish;
pub use super::course_publish_pre::Entity as CoursePublishPre;
pub use super::course_teacher::Entity as CourseTeacher;
pub use super::mq_message::Entity as MqMessage;
pub use super::mq_message_history::Entity as MqMessageHistory;
pub use super::teachplan::Entity as Teachplan;
pub use super::teachplan_media::Entity as TeachplanMedia;
pub use super::teachplan_work::Entity as TeachplanWork;
