//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teachplan_work")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub work_id: i64,
    pub work_title: String,
    pub teachplan_id: i64,
    pub course_id: Option<i64>,
    pub create_date: Option<DateTime>,
    pub course_pub_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
