//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "teachplan")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub pname: String,
    pub parentid: i64,
    pub grade: i16,
    pub media_type: Option<String>,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub description: Option<String>,
    pub timelength: Option<String>,
    pub orderby: Option<i32>,
    pub course_id: i64,
    pub course_pub_id: Option<i64>,
    pub status: i32,
    pub is_preview: Option<String>,
    pub create_date: Option<DateTime>,
    pub change_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
